### ISSUE TITLE
warning: `bdex` (bin "bdex") generated 2 warnings

### ISSUE THREAD

**Issue by xiaole3349** [Yesterday17/bdex-rs#1]
warning: field is never read: `time`
  --> src/main.rs:17:5
   |
17 |     time: u64,
   |     ^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field is never read: `size`
  --> src/main.rs:42:5
   |
42 |     size: usize,
   |     ^^^^^^^^^^^

**Comment by Yesterday17** [comment]
These fields exist but are not used in code. It might be good to print them somewhere.

**Comment by xiaole3349** [comment]
I got it, thank you!
